def increaseSellNumber(sellNumber):
    if str(sellNumber)[0] == "5":
        return sellNumber * 2
    else:
        return sellNumber * 5
def decreaseSellNumber(sellNumber):
    if sellNumber == 1:
        return sellNumber
    if str(sellNumber)[0] == "5":
        return sellNumber // 5
    else:
        return sellNumber // 2

# Test
nb = 1
nb = increaseSellNumber(nb)
print(nb)
nb = increaseSellNumber(nb)
print(nb)
nb = increaseSellNumber(nb)
print(nb)
nb = increaseSellNumber(nb)
print(nb)
nb = increaseSellNumber(nb)
print(nb)
nb = increaseSellNumber(nb)
print(nb)
nb = increaseSellNumber(nb)
print(nb)
nb = increaseSellNumber(nb)
print(nb)
nb = increaseSellNumber(nb)
print(nb)
nb = increaseSellNumber(nb)
print(nb)
nb = increaseSellNumber(nb)
print(nb)
nb = increaseSellNumber(nb)
print(nb)
nb = increaseSellNumber(nb)
print(nb)
nb = increaseSellNumber(nb)
print(nb)
nb = increaseSellNumber(nb)
print(nb)
nb = increaseSellNumber(nb)
print(nb)
nb = decreaseSellNumber(nb)
print(nb)
nb = decreaseSellNumber(nb)
print(nb)
nb = decreaseSellNumber(nb)
print(nb)
nb = decreaseSellNumber(nb)
print(nb)
nb = decreaseSellNumber(nb)
print(nb)
nb = decreaseSellNumber(nb)
print(nb)
nb = decreaseSellNumber(nb)
print(nb)
nb = decreaseSellNumber(nb)
print(nb)
nb = decreaseSellNumber(nb)
print(nb)
nb = decreaseSellNumber(nb)
print(nb)
nb = decreaseSellNumber(nb)
print(nb)
nb = decreaseSellNumber(nb)
print(nb)
nb = decreaseSellNumber(nb)
print(nb)
nb = decreaseSellNumber(nb)
print(nb)
nb = decreaseSellNumber(nb)
print(nb)
nb = decreaseSellNumber(nb)
print(nb)
nb = decreaseSellNumber(nb)
print(nb)
nb = decreaseSellNumber(nb)
print(nb)